### ISSUE TITLE
Program not working.

### ISSUE THREAD

**Issue by alakazam112** [kochsebastian/ChessVisionBot#2]
Hi,

Could you please look into the following error?

Using catalina macOS in vmware with anaconda3

```
Us to play: Calculating next move
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/alakazam/ChessVisionBot/code/game_state_classes.py", line 216, in play_next_move
    engine_process = self.engine.go(movetime=100)#(strength+(randint(1, variance)/1000)))
  File "/Users/alakazam/anaconda3/envs/chessbot/lib/python3.7/site-packages/chess/uci.py", line 1007, in go
    return self._queue_command(command, async_callback)
  File "/Users/alakazam/anaconda3/envs/chessbot/lib/python3.7/site-packages/chess/uci.py", line 688, in _queue_command
    return future.result(timeout=FUTURE_POLL_TIMEOUT)
  File "/Users/alakazam/anaconda3/envs/chessbot/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/Users/alakazam/anaconda3/envs/chessbot/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/alakazam/anaconda3/envs/chessbot/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/alakazam/anaconda3/envs/chessbot/lib/python3.7/site-packages/chess/uci.py", line 1003, in command
    raise EngineTerminatedException()
chess._engine.EngineTerminatedException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alakazam/anaconda3/envs/chessbot/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "ChessVisionBot/code/main.py", line 92, in start_playing
    score,winrate = game_state.play_next_move(position.factor,strength,variance)
  File "/Users/alakazam/ChessVisionBot/code/game_state_classes.py", line 219, in play_next_move
    except chess.engine.EngineTerminatedException:
AttributeError: module 'chess' has no attribute 'engine'
```

Please if you can add the readme its macOS only as some of the packages are mac only like quartz..

**Comment by kochsebastian** [comment]
Yeah so I am still working on the project and the readme has low priority for me right now. I am not planning to roll out a packaged version of the project partly to prevent that just anyone can download the project and start using this on a chess website. 
Feel free to get it to work on your platform I am sure the macOs dependencies are just supporting stuff and can be replaced by windows librariea you just have to look into it.

**Comment by alakazam112** [comment]
Yeah that make sense just like ripping off other ppl repo :)
https://github.com/Stanou01260/chessbot_python
