### ISSUE TITLE
Windows Stockfish load error

### ISSUE THREAD

**Issue by nirmalveer** [kochsebastian/ChessVisionBot#6]
`
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
`
  File "C:/Users/LiveL/Desktop/ChessVisionBot-master/code/main.py", line 56, in start_playing
    game_state = Game_state()
  File "C:\Users\LiveL\Desktop\ChessVisionBot-master\code\game_state_classes.py", line 47, in __init__
    self.engine = chess.engine.SimpleEngine.popen_uci("engine/stockfish-11-64")
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\engine.py", line 2440, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
`
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\engine.py", line 2432, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\engine.py", line 217, in run_in_background
    return future.result()
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\engine.py", line 211, in background
    _run(coroutine(future))
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\engine.py", line 2420, in background
    transport, protocol = await Protocol.popen(command, setpgrp=setpgrp, **popen_args)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\site-packages\chess\engine.py", line 912, in popen
    return await _get_running_loop().subprocess_exec(cls, *command, **popen_args)  # type: ignore
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_events.py", line 372, in _make_subprocess_transport
    **kwargs)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\asyncio\base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_events.py", line 819, in _start
    bufsize=bufsize, **kwargs)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\asyncio\windows_utils.py", line 155, in __init__
    stderr=stderr_wfd, **kwds)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\LiveL\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

**Comment by kochsebastian** [comment]
This seems to be a Windows issue as I have developed the project on a Mac. The problem seems to be with importing Stockfish.   
With this project I provided a Stockfish engine compatible with Mac. I think there are different versions for different operating system.   
Please download the Stockfish for Windows and then retry.
