### ISSUE TITLE
Loading file issue

### ISSUE THREAD

**Issue by beheshtiBlockchain** [kochsebastian/ChessVisionBot#9]
I am trying to run the python code but as it is shown up and clicked on start playing is showing this error:
`WARNING:TensorFlow: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-25-eae6e80082bc>", line 55, in start_playing
    game_state = Game_state()
  File "C:\Users\rayan gostar\Desktop\ChessVisionBot-master\code\game_state_classes.py", line 47, in __init__
    self.engine = chess.engine.SimpleEngine.popen_uci("./engine/stockfish-11-64")
  File "C:\Anaconda3\lib\site-packages\chess\engine.py", line 2452, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
  File "C:\Anaconda3\lib\site-packages\chess\engine.py", line 2444, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
  File "C:\Anaconda3\lib\site-packages\chess\engine.py", line 217, in run_in_background
    return future.result()
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Anaconda3\lib\site-packages\chess\engine.py", line 211, in background
    _run(coroutine(future))
  File "C:\Anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Anaconda3\lib\site-packages\chess\engine.py", line 2432, in background
    transport, protocol = await Protocol.popen(command, setpgrp=setpgrp, **popen_args)
  File "C:\Anaconda3\lib\site-packages\chess\engine.py", line 912, in popen
    return await _get_running_loop().subprocess_exec(cls, *command, **popen_args)  # type: ignore
  File "C:\Anaconda3\lib\asyncio\base_events.py", line 1533, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Anaconda3\lib\asyncio\windows_events.py", line 372, in _make_subprocess_transport
    **kwargs)
  File "C:\Anaconda3\lib\asyncio\base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "C:\Anaconda3\lib\asyncio\windows_events.py", line 819, in _start
    bufsize=bufsize, **kwargs)
  File "C:\Anaconda3\lib\asyncio\windows_utils.py", line 155, in __init__
    stderr=stderr_wfd, **kwds)
  File "C:\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

also, it seems that it cannot load the saved optimizer state.

**Comment by kochsebastian** [comment]
Please fill out the necessary details of the issue template so I can better understand your problem
